- name: download artifact
  get_url:
     url: https://github.com/Anji399/add/raw/master/target/add.war
     dest: /tmp
- name: copy artifact
  copy:
     src: /tmp/add.war
     dest: /opt/tomcat/webapps/add.war
     owner: tomcat
     group: tomcat
     remote_src: yes
 
